package config

const (
	ENV_KEY_PORT       = "SVC_PERCOLATOR_PORT"
	ENV_SVC_MANAGEMENT = "SVC_MANAGEMENT"

	ENV_ES_ADDR = "ES_ADDRESS"
	ENV_ES_USER = "ES_USERNAME"
	ENV_ES_PASS = "ES_PASSWORD"

	ENV_RDS_ADDR = "REDIS_ADDRESS"
	ENV_RDS_PASS = "REDIS_PASSWORD"
	ENV_RDS_DB   = "REDIS_DB"

	RDS_PREF_DATA       = "sumut:data-session"
	RDS_PREF_DATA_COUNT = "sumut:data-count"
)
